services:
    calendar-assistant:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=production
                - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-https://calendar-assistant.revisbali.com}
                - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-wss://calendar-assistant.revisbali.com}
                - NEXT_PUBLIC_DEBUG=${NEXT_PUBLIC_DEBUG:-false}
                - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-unknown}
        container_name: calendar-assistant
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - AUTH_SECRET=${AUTH_SECRET:-oqQSJAT9q1pn8cnFsrMgypU5OLe2qSFeaEd+vW0Cffs=}
            - NEXT_PWA_ENABLED=true
        env_file:
            - .env
        networks:
            - dockernet
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3000',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # Add resource limits
        deploy:
            resources:
                limits:
                    memory: 3G
                reservations:
                    memory: 1G

networks:
    dockernet:
        external: true
        name: dockernet
